Rails/sanganos/config/routes.rb
Sanganos::Application.routes.draw do
  resources :sanganos


end

Rails/sanganos/app/models/sangano.rb
class Sangano < ActiveRecord::Base
  attr_accessible :apellido, :descripcion, :name
  validates :name, presence: true
end

Rails/sanganos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Rails/sanganos/app/controllers/sanganos_controller.rb
class SanganosController < ApplicationController
  # GET /sanganos
  # GET /sanganos.json
  def index
    @sanganos = Sangano.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sanganos }
    end
  end

  # GET /sanganos/1
  # GET /sanganos/1.json
  def show
    @sangano = Sangano.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sangano }
    end
  end

  # GET /sanganos/new
  # GET /sanganos/new.json
  def new
    @sangano = Sangano.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sangano }
    end
  end

  # GET /sanganos/1/edit
  def edit
    @sangano = Sangano.find(params[:id])
  end

  # POST /sanganos
  # POST /sanganos.json
  def create
    @sangano = Sangano.new(params[:sangano])

    respond_to do |format|
      if @sangano.save
        format.html { redirect_to @sangano, notice: 'Sangano was successfully created.' }
        format.json { render json: @sangano, status: :created, location: @sangano }
      else
        format.html { render action: "new" }
        format.json { render json: @sangano.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sanganos/1
  # PUT /sanganos/1.json
  def update
    @sangano = Sangano.find(params[:id])

    respond_to do |format|
      if @sangano.update_attributes(params[:sangano])
        format.html { redirect_to @sangano, notice: 'Sangano was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sangano.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sanganos/1
  # DELETE /sanganos/1.json
  def destroy
    @sangano = Sangano.find(params[:id])
    @sangano.destroy

    respond_to do |format|
      format.html { redirect_to sanganos_url }
      format.json { head :no_content }
    end
  end
end

Rails/sanganos/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/sanganos/app/helpers/sanganos_helper.rb
module SanganosHelper
end

Rails/sanganos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sanganos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Rails/sanganos/app/views/sanganos/_form.html.erb
<%= form_for(@sangano) do |f| %>
  <% if @sangano.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sangano.errors.count, "error") %> prohibited this sangano from being saved:</h2>

      <ul>
      <% @sangano.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/sanganos/app/views/sanganos/edit.html.erb
<h1>Editing sangano</h1>

<%= render 'form' %>

<%= link_to 'Show', @sangano %> |
<%= link_to 'Back', sanganos_path %>

Rails/sanganos/app/views/sanganos/index.html.erb
<h1>Listing sanganos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Apellido</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sanganos.each do |sangano| %>
  <tr>
    <td><%= sangano.name %></td>
    <td><%= sangano.apellido %></td>
    <td><%= sangano.descripcion %></td>
    <td><%= link_to 'Show', sangano %></td>
    <td><%= link_to 'Edit', edit_sangano_path(sangano) %></td>
    <td><%= link_to 'Destroy', sangano, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sangano', new_sangano_path %>

Rails/sanganos/app/views/sanganos/new.html.erb
<h1>New sangano</h1>

<%= render 'form' %>

<%= link_to 'Back', sanganos_path %>

Rails/sanganos/app/views/sanganos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sangano.name %>
</p>

<p>
  <b>Apellido:</b>
  <%= @sangano.apellido %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @sangano.descripcion %>
</p>


<%= link_to 'Edit', edit_sangano_path(@sangano) %> |
<%= link_to 'Back', sanganos_path %>